# Generated by Django 4.1 on 2023-02-13 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='depression_articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.ImageField(upload_to='static/images')),
                ('article_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('article_description', models.CharField(blank=True, max_length=500, null=True)),
                ('article_link', models.URLField(default='#', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='mainscreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=500, null=True)),
                ('video_link', models.URLField(default='#', max_length=300)),
                ('depression_test_text', models.CharField(blank=True, max_length=500, null=True)),
                ('anxiety_test_text', models.CharField(blank=True, max_length=500, null=True)),
                ('depression_main_title', models.CharField(blank=True, max_length=500, null=True)),
                ('depression_main_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepressionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('quiz', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.CharField(blank=True, max_length=500, null=True)),
                ('educationallevel', models.CharField(blank=True, max_length=500, null=True)),
                ('maritalstatus', models.CharField(blank=True, max_length=500, null=True)),
                ('employmentstatus', models.CharField(blank=True, max_length=500, null=True)),
                ('province', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnxietyTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('quiz', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anxiety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('age', models.CharField(blank=True, max_length=500, null=True)),
                ('educationallevel', models.CharField(blank=True, max_length=500, null=True)),
                ('maritalstatus', models.CharField(blank=True, max_length=500, null=True)),
                ('employmentstatus', models.CharField(blank=True, max_length=500, null=True)),
                ('province', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
